### ISSUE TITLE
Runtime Error while testing motorTest.py

### ISSUE THREAD

**Issue by Tros-t** [xeecos/python-for-mbot#11]
Hi, So first of all I wanna thank the creator for making my life easier. And second while I am running the test for the motors the code is same as `from lib.mBot import *
bot = mBot()
#bot.startWithSerial("/dev/ttyUSB0")
bot.startWithSerial('COM3')
while(1):
	bot.doMove(100,100)
	sleep(2)
	bot.doMove(-100,-100)
	sleep(2)
	bot.doMove(0,0)
	sleep(2)`

And the Error I get is:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 114, in _main     
    prepare(preparation_data)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 225, in prepare   
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Ahmer Khan\Desktop\Arduino\python-for-mbot-master\motorTest.py", line 2, in <module>
    bot = mBot()
  File "c:\Users\Ahmer Khan\Desktop\Arduino\python-for-mbot-master\lib\mBot.py", line 104, in __init__
    self.manager = Manager()
  File "C:\Python37\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Python37\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
`

So kindly help me and I will create another issue for some more problems.

**Comment by Leemam555** [comment]
I have the same problem , can someone help me please ?
